### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by hmil** [senhungwong/http-exception-handler#3]
Hi, what a coincidence that you just published this module, I was looking for something like that just today!

I really like the idea of your project and I would like to suggest a few things:

### Type definitions

Would you accept to translate the project to TypeScript? This way TypeScript users will get proper type definitions out of the box, and JavaScript users won't be affected at all.
I already made all of the required changes in #1

### Express middleware

Your named the module after express, but there is nothing that comes out of the box to work with express. For now, your module provides **accurate and complete HTTP errors** which could be used in any context. I really like that.

But these exceptions are only useful if they are accompanied by a good express middleware. I started writing one in #2, but I am not sure if the express middleware belongs to this module.

I propose two things:
1. Either you rename the module to something more generic like `http-exceptions` (actually this name is already taken, but you get the point). So we know that this module is not targeting any specific framework
2. OR you provide a middleware for express similar to the one in my PR.

I think I would prefer solution 1 because then it is independent of the framework used, and your library remains more "pure". It could come with a companion library called "express-exception-handler" or similar to provide a middleware for express.

---

I want to emphasise again that I _really_ like your library. It is the only one I know of that takes this approach to solving the problem and I think it is the best approach. I hope you are open to my suggestions (especially the one about TypeScript), because I do not want to fork your library. I think if it is done well it could become a cornerstone of many web stacks.

**Comment by 5u4** [comment]
@hmil 
Thank you for having interest in this module. 

Translating them to TypeScript is definitely a great idea, thank you for doing that. 

About the naming issue, I agree with your first suggestion. I will come up with a more appropriate package name.

**Comment by 5u4** [comment]
Project is been moved to http-exceptions. Could you create the PR there again? Thank you again for your contribution!
